import { DiagramState, DiagramNode, DiagramContainer } from '../types';

export interface TerraformProjectFiles {
  'providers.tf': string;
  'main.tf': string;
  'variables.tf': string;
  'outputs.tf': string;
  'terraform.tfvars': string;
}

export const generateTerraformCode = (diagram: DiagramState): TerraformProjectFiles => {
  const providersSet = new Set<string>();
  diagram.nodes.forEach((node) => providersSet.add(node.provider));
  diagram.containers.forEach((c) => providersSet.add(c.provider));

  // 1. providers.tf
  let providersTf = `# Auto-generated by MultiCloud Canvas Studio on ${new Date().toLocaleDateString()}\n# Project: ${diagram.title}\n\nterraform {\n  required_version = ">= 1.5.0"\n  required_providers {\n`;

  if (providersSet.has('aws')) {
    providersTf += `    aws = {\n      source  = "hashicorp/aws"\n      version = "~> 5.0"\n    }\n`;
  }
  if (providersSet.has('azure')) {
    providersTf += `    azurerm = {\n      source  = "hashicorp/azurerm"\n      version = "~> 3.0"\n    }\n`;
  }
  if (providersSet.has('gcp')) {
    providersTf += `    google = {\n      source  = "hashicorp/google"\n      version = "~> 5.0"\n    }\n`;
  }
  if (providersSet.has('oci')) {
    providersTf += `    oci = {\n      source  = "oracle/oci"\n      version = ">= 5.0.0"\n    }\n`;
  }
  providersTf += `  }\n}\n\n`;

  if (providersSet.has('aws')) {
    providersTf += `provider "aws" {\n  region = var.aws_region\n  default_tags {\n    tags = {\n      Environment = var.environment\n      ManagedBy   = "MultiCloud-Canvas-Studio"\n    }\n  }\n}\n\n`;
  }
  if (providersSet.has('azure')) {
    providersTf += `provider "azurerm" {\n  features {}\n}\n\n`;
  }
  if (providersSet.has('gcp')) {
    providersTf += `provider "google" {\n  project = var.gcp_project_id\n  region  = var.gcp_region\n}\n\n`;
  }
  if (providersSet.has('oci')) {
    providersTf += `provider "oci" {\n  tenancy_ocid = var.oci_tenancy_ocid\n  region       = var.oci_region\n}\n\n`;
  }

  // 2. main.tf
  let mainTf = `# =========================================================\n# MAIN INFRASTRUCTURE CONFIGURATION\n# Architecture: ${diagram.title}\n# =========================================================\n\n`;

  // Render Containers (VPCs, Subnets, Resource Groups)
  diagram.containers.forEach((c) => {
    const sanitizeId = c.id.replace(/[^a-zA-Z0-9_]/g, '_');
    if (c.provider === 'aws') {
      if (c.type === 'vpc') {
        mainTf += `# AWS VPC Container: ${c.name}\nresource "aws_vpc" "${sanitizeId}" {\n  cidr_block           = "10.0.0.0/16"\n  enable_dns_hostnames = true\n  enable_dns_support   = true\n  tags = {\n    Name = "${c.name}"\n  }\n}\n\n`;
      } else if (c.type === 'subnet') {
        mainTf += `# AWS Subnet: ${c.name}\nresource "aws_subnet" "${sanitizeId}" {\n  vpc_id                  = aws_vpc.c_vpc.id\n  cidr_block              = "10.0.1.0/24"\n  map_public_ip_on_launch = ${c.isPublicSubnet ? 'true' : 'false'}\n  tags = {\n    Name = "${c.name}"\n  }\n}\n\n`;
      }
    } else if (c.provider === 'azure') {
      mainTf += `# Azure Resource Group: ${c.name}\nresource "azurerm_resource_group" "${sanitizeId}" {\n  name     = "rg-${sanitizeId}"\n  location = var.azure_region\n}\n\n`;
    } else if (c.provider === 'gcp') {
      mainTf += `# GCP Network: ${c.name}\nresource "google_compute_network" "${sanitizeId}" {\n  name                    = "${sanitizeId.toLowerCase()}-vpc"\n  auto_create_subnetworks = true\n}\n\n`;
    } else if (c.provider === 'oci') {
      mainTf += `# OCI VCN: ${c.name}\nresource "oci_core_vcn" "${sanitizeId}" {\n  cidr_block     = "10.0.0.0/16"\n  compartment_id = var.oci_compartment_id\n  display_name   = "${c.name}"\n}\n\n`;
    }
  });

  // Render Nodes
  diagram.nodes.forEach((node) => {
    const sanitizeId = node.id.replace(/[^a-zA-Z0-9_]/g, '_');
    const name = node.name;
    const resType = node.resourceType || getFallbackResourceType(node);

    mainTf += `# Node: ${name} (${node.provider.toUpperCase()})\n`;

    switch (node.iconKey) {
      case 'aws_ec2':
        mainTf += `resource "aws_instance" "${sanitizeId}" {\n  count         = ${node.specs.count || 1}\n  ami           = "ami-0c55b159cbfafe1f0"\n  instance_type = "${node.specs.instanceType || 't3.medium'}"\n  tags = {\n    Name = "${name}"\n  }\n}\n\n`;
        break;
      case 'aws_s3':
        mainTf += `resource "aws_s3_bucket" "${sanitizeId}" {\n  bucket_prefix = "${sanitizeId.toLowerCase()}-"\n  force_destroy = true\n  tags = {\n    Name = "${name}"\n  }\n}\n\n`;
        break;
      case 'aws_rds':
        mainTf += `resource "aws_db_instance" "${sanitizeId}" {\n  allocated_storage   = ${node.specs.storageGb || 100}\n  engine              = "${node.specs.engine || 'postgres'}"\n  engine_version      = "15.3"\n  instance_class      = "${node.specs.instanceType || 'db.r6g.xlarge'}"\n  username            = "dbadmin"\n  password            = "ChangeMeInProduction123!"\n  skip_final_snapshot = true\n  tags = {\n    Name = "${name}"\n  }\n}\n\n`;
        break;
      case 'aws_alb':
        mainTf += `resource "aws_lb" "${sanitizeId}" {\n  name               = "${sanitizeId.toLowerCase()}-alb"\n  internal           = false\n  load_balancer_type = "application"\n  tags = {\n    Name = "${name}"\n  }\n}\n\n`;
        break;
      case 'aws_cloudfront':
        mainTf += `resource "aws_cloudfront_distribution" "${sanitizeId}" {\n  enabled = true\n  comment = "${name}"\n  origin {\n    domain_name = "example.s3.amazonaws.com"\n    origin_id   = "S3-Origin"\n  }\n  viewer_certificate {\n    cloudfront_default_certificate = true\n  }\n  restrictions {\n    geo_restriction {\n      restriction_type = "none"\n    }\n  }\n}\n\n`;
        break;
      case 'azure_vm':
        mainTf += `resource "azurerm_linux_virtual_machine" "${sanitizeId}" {\n  name                = "${sanitizeId.toLowerCase()}-vm"\n  resource_group_name = "rg-main"\n  location            = var.azure_region\n  size                = "${node.specs.instanceType || 'Standard_D2s_v3'}"\n  admin_username      = "azureuser"\n  os_disk {\n    caching              = "ReadWrite"\n    storage_account_type = "Standard_LRS"\n  }\n  source_image_reference {\n    publisher = "Canonical"\n    offer     = "0001-com-ubuntu-server-jammy"\n    sku       = "22_04-lts"\n    version   = "latest"\n  }\n}\n\n`;
        break;
      case 'gcp_gce':
        mainTf += `resource "google_compute_instance" "${sanitizeId}" {\n  name         = "${sanitizeId.toLowerCase()}-vm"\n  machine_type = "${node.specs.instanceType || 'e2-standard-2'}"\n  zone         = "\${var.gcp_region}-a"\n  boot_disk {\n    initialize_params {\n      image = "debian-cloud/debian-11"\n    }\n  }\n  network_interface {\n    network = "default"\n  }\n}\n\n`;
        break;
      case 'gcp_cloud_sql':
        mainTf += `resource "google_sql_database_instance" "${sanitizeId}" {\n  name             = "${sanitizeId.toLowerCase()}-db"\n  database_version = "POSTGRES_15"\n  region           = var.gcp_region\n  settings {\n    tier = "${node.specs.instanceType || 'db-custom-2-7680'}"\n  }\n}\n\n`;
        break;
      case 'oci_compute':
        mainTf += `resource "oci_core_instance" "${sanitizeId}" {\n  availability_domain = "AD-1"\n  compartment_id      = var.oci_compartment_id\n  shape               = "${node.specs.instanceType || 'VM.Standard2.1'}"\n  display_name        = "${name}"\n}\n\n`;
        break;
      case 'oci_autonomous_db':
        mainTf += `resource "oci_database_autonomous_database" "${sanitizeId}" {\n  compartment_id           = var.oci_compartment_id\n  db_name                  = "${sanitizeId.toLowerCase()}"\n  cpu_core_count           = 1\n  data_storage_size_in_tbs = 1\n  display_name             = "${name}"\n}\n\n`;
        break;
      default:
        mainTf += `resource "${resType}" "${sanitizeId}" {\n  # Specs: ${JSON.stringify(node.specs)}\n  # Provider: ${node.provider}\n}\n\n`;
        break;
    }
  });

  // 3. variables.tf
  let varsTf = `# Variables definition\n\nvariable "environment" {\n  type        = string\n  default     = "production"\n  description = "Target deployment environment"\n}\n\n`;

  if (providersSet.has('aws')) {
    varsTf += `variable "aws_region" {\n  type        = string\n  default     = "us-east-1"\n  description = "Primary AWS region"\n}\n\n`;
  }
  if (providersSet.has('azure')) {
    varsTf += `variable "azure_region" {\n  type        = string\n  default     = "eastus"\n  description = "Azure datacenter location"\n}\n\n`;
  }
  if (providersSet.has('gcp')) {
    varsTf += `variable "gcp_project_id" {\n  type        = string\n  default     = "my-gcp-project-123"\n  description = "GCP Project ID"\n}\n\nvariable "gcp_region" {\n  type        = string\n  default     = "us-central1"\n}\n\n`;
  }
  if (providersSet.has('oci')) {
    varsTf += `variable "oci_tenancy_ocid" {\n  type        = string\n  default     = "ocid1.tenancy.oc1..example"\n}\n\nvariable "oci_compartment_id" {\n  type        = string\n  default     = "ocid1.compartment.oc1..example"\n}\n\nvariable "oci_region" {\n  type        = string\n  default     = "us-ashburn-1"\n}\n\n`;
  }

  // 4. outputs.tf
  let outputsTf = `# Infrastructure Outputs\n\n`;
  diagram.nodes.forEach((node) => {
    const sanitizeId = node.id.replace(/[^a-zA-Z0-9_]/g, '_');
    if (node.iconKey === 'aws_ec2') {
      outputsTf += `output "${sanitizeId}_public_ip" {\n  value       = aws_instance.${sanitizeId}[*].public_ip\n  description = "Public IP addresses for ${node.name}"\n}\n\n`;
    } else if (node.iconKey === 'aws_s3') {
      outputsTf += `output "${sanitizeId}_bucket_name" {\n  value       = aws_s3_bucket.${sanitizeId}.id\n}\n\n`;
    } else if (node.iconKey === 'aws_alb') {
      outputsTf += `output "${sanitizeId}_dns_name" {\n  value       = aws_lb.${sanitizeId}.dns_name\n}\n\n`;
    }
  });

  // 5. terraform.tfvars
  let tfvars = `# Sample Terraform environment variables\nenvironment = "production"\n`;
  if (providersSet.has('aws')) tfvars += `aws_region  = "us-east-1"\n`;
  if (providersSet.has('azure')) tfvars += `azure_region = "eastus"\n`;
  if (providersSet.has('gcp')) {
    tfvars += `gcp_project_id = "my-company-prod-cloud"\ngcp_region = "us-central1"\n`;
  }

  return {
    'providers.tf': providersTf,
    'main.tf': mainTf,
    'variables.tf': varsTf,
    'outputs.tf': outputsTf,
    'terraform.tfvars': tfvars
  };
};

const getFallbackResourceType = (node: DiagramNode): string => {
  switch (node.provider) {
    case 'aws': return 'aws_custom_resource';
    case 'azure': return 'azurerm_resource';
    case 'gcp': return 'google_custom_resource';
    case 'oci': return 'oci_custom_resource';
    default: return 'custom_resource';
  }
};
